name: Build docker latest image
on:
  # schedule:
  #   - cron: '0 0 * * 1,3,6' # @at 0h0m0s every 3 days
  push:
    tags: ['v*.*.*']
    branches: [master]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      #
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=mdouchement/standardfile

          VERSION=edge
          if [[ $GITHUB_REF == refs/heads/* ]]; then
            # Branch name
            VERSION=${GITHUB_REF#refs/heads/}
          fi
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            # Tag name
            VERSION=${GITHUB_REF#refs/tags/v}
          fi

          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:latest"
          fi

          echo ::set-output name=tags::${TAGS}
      #
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      #
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      #
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.prep.outputs.tags }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}