on:
- push
- pull_request
name: Test
env:
  GO_VERSION: "~1"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    #
    # Workaround until https://github.com/actions/setup-go/pull/184 merged
    - name: Remove Golang from cache
      run: rm -rf ${RUNNER_TOOL_CACHE}/go
    #
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go
    - name: Tooling
      run: go install gotest.tools/gotestsum@latest
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: gotestsum
