on:
- push
- pull_request
name: Test
env:
  GO_VERSION: "~1"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    #
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
        check-latest: true
    - name: Tooling
      run: go install gotest.tools/gotestsum@latest
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      run: gotestsum
